An feed test
zetaapps/myntra pull request #14
Opened 2017-05-10 07:15 UTC by arunnandewal

completed feed test cases please review

2017-05-10 16:17 UTC, manjunathc23 requested changes
@arunnandewal : You may want to consider to mark final for all API layer variables.

2017-05-10 16:17 UTC, manjunathc23 commented on thunderbird/src/main/java/zeta/android/thunderbird/api/devapi/response/feed/FeedShareResponse.java
> +    public String ogImageUrl;
`public final` please

2017-05-10 17:10 UTC, muditpant13 commented on thunderbird/src/main/java/zeta/android/thunderbird/api/devapi/response/feed/FeedShareResponse.java
> +    public String ogImageUrl;
+1

2017-06-24 07:23 UTC, manjunathc23 commented
This was rebased and merged into master. Thanks @arunnandewal

2017-06-24 07:23 UTC, closed without merging